### ISSUE TITLE
Adding Kubernetes Labels

### ISSUE THREAD

**Issue by crigor** [draganm/missing-container-metrics#1]
Thank you for this project! I'm evaluating it now on our kubernetes cluster. It is working and I'm seeing data being collected. I'm interested specifically in container_ooms.

Is it possible to add Kubernetes pod labels to the metrics? Or how do you query the data to show the number of container_ooms for a particular Kubernetes deployment? I'm looking at `pod` and I have something like `pod="web-puma-7c84796c86-6blt7"`. I would like to create a dashboard that shows the number of container_ooms for the web-puma deployment.

In case it matters, I'm using Datadog to view the metrics. The Prometheus labels are converted to Datadog tags, and by viewing localhost:3001/metrics, I don't think I'm missing any data provided by missing-container-metrics. The closest thing that works is grouping by `image_id` but that changes when we build a new image.

**Comment by draganm** [comment]
Glad you're finding it useful! I've never tried to use this together with Datadog, but with Prometheus, you can combine the `container_ooms` with `kube_pod_labels` (joining by pod name and namespace) or even better `kube_pod_info` which will give you the ReplicaSet name (`created_by_name`) and then you can combine that with `kube_replicaset_owner` metric to get the deployment that owns it .. at the end of the day it is a very uggly PromQL, but should be able to determine the 'owner' of the pod.

**Comment by crigor** [comment]
Thank you for the reply @draganm. I don't think `kube_pod_info`, etc is available to me but good to know this if I use Prometheus in the future.

I looked into adding the labels to missing-container-metrics, but the problem is since missing-container-metrics look at docker labels, it's limited to what exists on docker. And kubelet isn't flexible to add arbitrary labels to docker labels.

Thanks again for the project! It's really useful to us.
