### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by bdronneau** [draganm/missing-container-metrics#17]
Hello,

Thank for provide this exporter.
Do you have any plan for support arm (raspberry) build ?

Best

**Comment by cablespaghetti** [comment]
I've got a fork of this with a few minor changes. The latest and `0.24.0` tags have arm64 builds if you're on a 64bit OS on your Pi. https://github.com/cablespaghetti/missing-container-metrics

**Comment by bdronneau** [comment]
I'll give a try
